# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "bcchapi" = super.buildPythonPackage rec {
    pname = "bcchapi";
    version = "1.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/94/b6ca41a74feb6a0dc696386f616024b72e9fc3af200cffacc9ce4233e7d5/bcchapi-1.1.2-py3-none-any.whl";
      sha256 = "1pi720rh7mim2apglk5idd1xx0nl3lp2g9rvya1sw6vrwq323hqh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pandas"
      self."requests"
    ];
  };
}
